const CHANGE_STATE_BACKBONE = 'CHANGE_STATE_BACKBONE';

const CAMPAIGN_REQUEST = 'CAMPAIGN_OPEN_REQUEST';
const CAMPAIGN_RECEIVE = 'CAMPAIGN_OPEN_RECEIVE';
const CAMPAIGN_CHANGE  = 'CAMPAIGN_CHANGE';
